webtalk_init -webtalk_dir D:/Polimi/2.Semester/Digital Electronic Systems Design/Lab Furkan Test Local Files/LAB1/Group LAB1/PulseGenerator_test/PulseGenerator/PulseGenerator.sim/sim_1/behav/xsim/xsim.dir/tb_PulseGenerator_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Apr  3 02:10:24 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a0c24b87-fa76-4ac4-8cf3-fad49f9b3c38" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2abf3b521dcc4c88813c75023ebcfb98" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6612_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1027015283 -regid "" -xml D:/Polimi/2.Semester/Digital Electronic Systems Design/Lab Furkan Test Local Files/LAB1/Group LAB1/PulseGenerator_test/PulseGenerator/PulseGenerator.sim/sim_1/behav/xsim/xsim.dir/tb_PulseGenerator_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Polimi/2.Semester/Digital Electronic Systems Design/Lab Furkan Test Local Files/LAB1/Group LAB1/PulseGenerator_test/PulseGenerator/PulseGenerator.sim/sim_1/behav/xsim/xsim.dir/tb_PulseGenerator_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Polimi/2.Semester/Digital Electronic Systems Design/Lab Furkan Test Local Files/LAB1/Group LAB1/PulseGenerator_test/PulseGenerator/PulseGenerator.sim/sim_1/behav/xsim/xsim.dir/tb_PulseGenerator_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
